#!/usr/bin/python3
import sys
import os
import json
import requests

def send_code_to_slack(code):
  code = {"text": code}
  code = json.dumps(code)
  token=os.environ['SLACK_API_TOKEN']
  url = f'https://hooks.slack.com/services/{token}'
  resp = requests.post(url, code)
  print(resp)

if __name__ == '__main__':
  # Get the filename from the first argument passed to the script.
  filename = sys.argv[1]
  try:
    title = sys.argv[2]
  except:
    title = 'SCAN Summary'

  # Read the contents of the text file.
  with open(filename, "r") as f:
    code = f.read()

  array = []
  for i in range(0, len(code), 2048):
    array.append(code[i:i + 2048])


  # Send the code to the Slack channel as code.
  for code in array:
    print(f'[+] Sending: {code}')
    code = f'{title}\n```{code}```'
    send_code_to_slack(code)


