#!/usr/bin/python3
from slack_sdk.webhook import WebhookClient
import sys
import os


def send_code_to_slack(code):
  token=os.environ['SLACK_API_TOKEN']
  url = f'https://hooks.slack.com/services/{token}'
  webhook = WebhookClient(url)

  response = webhook.send(text=code)
  assert response.status_code == 200
  assert response.body == "ok"


if __name__ == '__main__':
  # Get the filename from the first argument passed to the script.
  filename = sys.argv[1]

  # Read the contents of the text file.
  with open(filename, "r") as f:
    code = f.read()
  code = f'SCAN Summary\n```{code}```'

  # Send the code to the Slack channel as code.
  send_code_to_slack(code)


